# Omission Figures Module
from .fig1_theory import generate_figure_1
from .fig2_psth import generate_figure_2
from .fig3_surprise import generate_figure_3
from .fig4_coding import generate_figure_4
from .fig5_tfr import generate_figure_5
from .fig6_band_power import generate_figure_6
from .fig7_sfc import generate_figure_7
from .fig8_coordination import generate_figure_8
